# prettier-ignore

version: "3"
services:
  express:
    build:
      context: .
    ports:
      - 3001:3001
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      MONGODB_URI: "${MONGODB_URI}"
      MONGODB_URI_LOCAL: "${MONGODB_URI_LOCAL}"
      JWT_SECRET: "${JWT_SECRET}"
      PORT: "${PORT}"
      GOOGLE_CLIENT_ID:  "${GOOGLE_CLIENT_ID}"
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume: 